minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@takeyaqa/pict-wasm"
trustPolicy: no-downgrade
trustPolicyExclude:
  - rollup
  - semver
  - undici-types
onlyBuiltDependencies:
  - esbuild
  - sharp
