minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@takeyaqa/pict-wasm"
trustPolicy: no-downgrade
trustPolicyExclude:
  - "@trickfilm400/rollup-plugin-off-main-thread"
  - semver
onlyBuiltDependencies:
  - sharp
