name: deploy
on:
  release:
    types: [published]

env:
  PNPM_VERSION: 10
  NODE_VERSION: 22
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
        env:
          VITE_APP_VERSION: ${{ github.event.release.tag_name }}
          VITE_BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}
          VITE_NOTIFICATION_MESSAGE: ${{ vars.NOTIFICATION_MESSAGE }}
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy dist --project-name=pictrider --branch=main
